Add troubleshooting document, include initial examples - ledger connection, out-of-sync RevReg
openwallet-foundation/acapy pull request #1818
Opened 2022-06-16 18:56 UTC by swcurran

Signed-off-by: Stephen Curran <swcurran@gmail.com>

2022-06-16 19:02 UTC, swcurran commented
@WadeBarnes @ianco -- please take a look.  In a comment here, feel free to suggest other troubleshooting problems that we should include in this document.

Is the document a good idea?  Is the content sufficient? I couldn't think of where else to document the RevReg fixing stuff.

I believe we need an issue (and a PR) that is intended to prevent the "out of sync" scenario - correct?

2022-06-21 15:38 UTC, WadeBarnes requested changes
Endpoint paths not displaying the `<id>` parameter.

2022-06-21 15:38 UTC, WadeBarnes commented on Troubleshooting.md
> +- GET /revocation/registry/<id>/issued - counts of the number of issued/revoked
```suggestion
- GET `/revocation/registry/<id>/issued` - counts of the number of issued/revoked
```

2022-06-21 15:38 UTC, WadeBarnes commented on Troubleshooting.md
> +- GET /revocation/registry/<id>/issued/indy_recs - calculated rev_reg_delta from
```suggestion
- GET `/revocation/registry/<id>/issued/indy_recs` - calculated rev_reg_delta from
```

2022-06-21 17:06 UTC, swcurran commented on Troubleshooting.md
> +- PUT /revocation/registry/<id>/fix-revocation-entry-state - publish an update
Good catch -- thanks.  Fixed.

2022-06-21 17:07 UTC, swcurran commented
@WadeBarnes -- please take another look.

2022-06-21 17:38 UTC, WadeBarnes approved these changes

2022-06-21 18:29 UTC, merged