refactor: remove connection protocol
openwallet-foundation/acapy pull request #3184
Opened 2024-08-19 21:20 UTC by dbluhm

This PR Removes the deprecated connections protocol.

In addition to the message handlers and routes, this also means:
- CLI flags relating to connections protocol removed.
- References to specific messages in base connection manager were removed; there will need to be some working around this in the plugin to continue to support the protocol but I think it's good and necessary to at least rip it out for now here.
- Introduction protocol used to use Connections invitations. I did a very rough-and-ready conversion to OOB invites.

I am expecting this to not be fully functional yet so opening as a draft for now.

2024-08-20 16:30 UTC, PatStLouis commented
@dbluhm it was mentioned on the call this was moved to a plugin. Is the code to enable using that plugin included in this pr?

2024-08-20 17:20 UTC, swcurran commented
It’s in the plugin repo: https://github.com/hyperledger/aries-acapy-plugins/pull/925

2024-08-20 17:24 UTC, PatStLouis commented
@swcurran thank you, I was referring towards the "code required to make this plugin work" which was highlighted in the meeting. 

The functionality lost/broken features [outlined here](https://github.com/hyperledger/aries-acapy-plugins/pull/925#issuecomment-2297477787), will this require code from within the aca-py code base or it can all be managed in the external plugin?

2024-08-20 17:27 UTC, swcurran commented
Doh…sorry about that. Good point.  And per my comment in the meeting — is it viable to simply document how to use the plugin?  I suppose not being able to use the artifacts directly (e.g., having to change the Python code) might be a bit too painful.

2024-09-19 15:11 UTC, dbluhm commented
With the most recent updates on this branch and to the corresponding plugin, I have successfully completed a connection using the plugged in connection protocol. There are some failing tests I will address but I will go ahead and mark this as ready for review.

2024-09-23 16:58 UTC, jamshale reviewed
This looks great! I think this deprecation support path is really going to help manage complexity.

I'm just wondering if maybe a scenario test that installs the plugin and creates a v1 connection might be a good idea.

I don't see any reason not to approve this. We'll need good docs for when it gets released. Guaranteed people are going to upgrade without realizing this change has happened.

2024-09-23 17:22 UTC, swcurran commented
Cool.  Let’s include in our discussion tomorrow the version number if we remove this.  1.1.0?  

Should the SonarCloud analysis be addressed before merging?

2024-09-23 19:33 UTC, dbluhm commented
> I'm just wondering if maybe a scenario test that installs the plugin and creates a v1 connection might be a good idea.

We can do that though this is basically what's happening in the integration test of the plugin itself. So I'm not sure how valuable it is for it to be tested in both places.

> We'll need good docs for when it gets released.

Indeed, I have not adequately addressed this need yet.

> Should the SonarCloud analysis be addressed before merging?

I am not too concerned personally. The most complaints are coming from code that was just moved but detected as new in the connection routes (moved from the protocols.connections.routes to connections.routes).

2025-01-22 20:01 UTC, dbluhm commented
This PR has been refreshed after growing stale. It is ready for review and merge whenever we're ready with it.

2025-01-22 21:47 UTC, swcurran commented
@jamshale @loneil and other @openwallet-foundation/acapy-admins and @openwallet-foundation/acapy-committers -- please review and let's get this merged before it goes stale again.  I love the "new code not tested" since this is a PR about removal... I assume we can ignore that, but would like a dev to review/comment.

Thanks

2025-01-23 00:15 UTC, jamshale approved these changes
I can't find anything wrong with this. Looks good to me 👍 . Happy to get all this complexity removed from the core.

The most important thing is the plugin works...

2025-01-23 13:40 UTC, ff137 requested changes

2025-01-23 13:40 UTC, ff137 commented on acapy_agent/protocols/connections/v1_0/tests/test_routes.py
> -    async def test_connections_list(self):
Some of these tests should not be deleted, because they are still kept in the connections routes module. That's why SonarCloud reports the uncovered lines. Can use [their report](https://sonarcloud.io/component_measures?id=openwallet-foundation_acapy&pullRequest=3184&metric=new_coverage&selected=openwallet-foundation_acapy%3Aacapy_agent%2Fconnections%2Froutes.py) to check which tests should remain

2025-01-23 17:37 UTC, swcurran approved these changes

2025-01-23 17:38 UTC, merged

2025-01-23 18:04 UTC, ff137 commented on acapy_agent/protocols/connections/v1_0/tests/test_routes.py
> -    async def test_connections_list(self):
I still think it's a good idea to re-add those unit tests :eyes:

2025-01-23 18:37 UTC, swcurran commented
Sorry — I junped the gun on this one. I also should have waited until the connections plugin was in place.  I think there will be some falling out with this one before it is complete.

2025-01-23 19:27 UTC, ianco commented
> Sorry — I junped the gun on this one. I also should have waited until the connections plugin was in place. I think there will be some falling out with this one before it is complete.

Also this is now breaking some OATH tests tat are still using connection protocol ...

2025-01-23 19:59 UTC, swcurran commented
Yes — expected. Part of the fix/cleanup will be adding the plugin.  We’ll just live with it for now — I’ll try to deal with it later.  @ianco — much more concerned  about getting the intermittent fix resolved in OATH and integration tests here.

2025-01-24 03:21 UTC, dbluhm commented on acapy_agent/protocols/connections/v1_0/tests/test_routes.py
> -    async def test_connections_list(self):
Ah, good catch, I intended to move these tests along with the routes.py file to the core connections package. I will open a PR restoring these tests (the ones that are still relevant).